title: Mohamed Refaay Blogs
# هذا السطر يغير كلمة Blogs التي تظهر أحياناً في ترويسة الموقع
description: >-
  متخصص في حلول البنية التحتية، Nutanix، و Azure Stack HCI.

# روابط السوشيال ميديا (ضع اسم المستخدم الخاص بك فقط)
github_username:  mrefaay89
linkedin_username: mohamed-refaay-6b49a0120 # تأكد من اسم المستخدم الخاص بك في لينكد إن

# إعدادات القالب
theme: minima
plugins:
  - jekyll-feed
